### PR TITLE
Add `filter` arg to `aws_billing()` for Filter parameter in Cost Explorer Get Cost and Usage

### LINKED ISSUE #72: Billing: handle `RECORD_TYPE` via filter or group_by
Love where this package is going, so nice to see a "humane" approach to interacting with AWS!

I am using the billing functions, which to this point I have been [rolling for myself](https://github.com/NASA-Openscapes/2i2cAccessPolicies/pull/13/files#diff-d5fb2d022a1c7396fdfb20f19d15a4241f431df996438ad4bd47e25f115e2566). The `aws_billing()` is great for its simplicity, and I wonder if it can be more generalizable. 

My specific use-case is that in our current account, all of our usage is paid for by credits as the usage occurs. By default, the cost explorer API returns net costs by time period aggregated over all charge types, so our net daily cost comes out as zero (== usage - credits). I can deal with this in two ways - add a `GroupBy` parameter so it groups by [`RECORD_TYPE`](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/manage-cost-categories.html#cost-categories-terms) (`list(Type = "DIMENSION", Key = "RECORD_TYPE")`), and then I can filter locally to just get usage records. Or I can add a `Filter` statement to the CE query to just get `RECORD_TYPE == "Usage"`, which is what [I am currently doing](https://github.com/NASA-Openscapes/2i2cAccessPolicies/blob/a57157190e92ee7871af3ac4f4e4ef042a03e17f/aws-usage-report/aws-usage-report.qmd#L120-L123).

Apparently only two values for `GroupBy` are allowed, and since [GroupBy already has two values in `billing_factory()`](https://github.com/getwilds/sixtyfour/blob/13aade6a2440a6b82d307d5d29cacaad350b0140/R/billing.R#L78-L81), I wonder if allowing a user to pass a filter in through `aws_billing()` to `aws_billing_raw()` would be desirable? It actually looks like the plumbing was started as there is an [unused `filter` argument](https://github.com/getwilds/sixtyfour/blob/13aade6a2440a6b82d307d5d29cacaad350b0140/R/billing.R#L140) already there. 

I'd be happy to start a PR if this would be of interest?

(PS Hey @sckott 👋! And @seankross - hopefully you don't start to regret asking me to kick the tires! 😉)

### PR DESCRIPTION
**Pull request by ateucher**
## Description
Sorry, this has been a while in coming! This allows filtering of Get Cost and Usage queries. Adds `filter` argument to `aws_billing()`, passed through to `aws_billing_raw()`, making use of the `Filter` argument in [`ce$get_cost_and_usage()` in paws](https://www.paws-r-sdk.com/docs/costexplorer_get_cost_and_usage/#arguments)

## Related Issue
Closes #72 

## Example
```r
aws_billing(
  date_start = as.character(Sys.Date() - 30),
  filter = list(
    Dimensions = list(
      Key = "RECORD_TYPE",
      Values = "Usage"
    )
  )
)
```

## Testing
There aren't currently any tests for billing. Looking at LocalStack, [it looks like you need the pro version for the Cost Explorer API](https://docs.localstack.cloud/references/coverage/coverage_ce/). Do you have thoughts on how to enable testing for `aws_billing()`?

### CODE REVIEW

**Comment by ateucher** [comment]
Just a thought - to keep this more 'humane', The exported function could probably take a named vector rather than a nested list, so the user's call would look more like:

```r
aws_billing(
  date_start = as.character(Sys.Date() - 30),
  filter = c("RECORD_TYPE" = "Usage")
)
```

**Comment by sckott** [comment]
Thanks @ateucher - So sorry about the delay in getting back to you. I'm not sure how I missed this. 

Looking good, a few things on linting:

- Can you prune any whitespace in the billing.R file
- Can you make lines no wider than 80 chars, or put a `#nolint` at the end of those lines

Example works well for me, very nice!

For tests, correct, we don't have an easy way of testing billing functionality. Correct, we'd need a pro version of LocalStack, and we don't have that. Perhaps we can build some mocks from real requests and change details sufficiently and then use those ...

**Comment by sckott** [comment]
> Just a thought - to keep this more 'humane', 

Seems like a good idea to me. However, I'm not super familiar with all the options here. @seankross DO you have an opinion on this? Some possible options:

- have `filter` accept two types of inputs. a) of the form nested list form that's more complicated, and b) some simplified form like a named vector OR this could be a function like `billing_filter()` that could construct that nested list without the user having to do it themselves. 
- or two separate params for the nested list and simplified forms
- or just only allow the nested list.

**Comment by ateucher** [comment]
> > Just a thought - to keep this more 'humane',
> 
> Seems like a good idea to me. However, I'm not super familiar with all the options here. @seankross DO you have an opinion on this? Some possible options:
> 
> * have `filter` accept two types of inputs. a) of the form nested list form that's more complicated, and b) some simplified form like a named vector OR this could be a function like `billing_filter()` that could construct that nested list without the user having to do it themselves.
> * or two separate params for the nested list and simplified forms
> * or just only allow the nested list.

Personally I don't like the idea of two parameters. I'd suggest option 1 or 3, but lean towards 3 (with the examples hopefully providing enough context to construct the simplest filter). If we go with option 1, I like 1a.  Easy to switch the internal logic based on the input type, and I think creating a function that would reliably create a valid list with the appropriate `AND`s, `OR`s etc would be challenging.

**Comment by sckott** [comment]
Thanks I'll check out that test!

**Comment by sckott** [comment]
> Personally I don't like the idea of two parameters. I'd suggest ...

Okay, yeah happy to just accept the nested list and make sure we have lots of examples though

**Comment by sckott** [comment]
okay that test for rds should be fixed on main now.

**Comment by sckott** [comment]
@ateucher  Can you add some more examples to the aws_billing fxn showing some more varied examples?

**Comment by ateucher** [comment]
@sckott added a few more examples

**Comment by sckott** [comment]
Awesome, thanks @ateucher !

Let's merge this. I'm still working on the test stubs (#76 ) but once that's sorted out then will come back to add tests for billing.

**Pull request merged**
